# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/action_message_boxUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ActionMessageBoxDialog(object):
    def setupUi(self, ActionMessageBoxDialog):
        ActionMessageBoxDialog.setObjectName("ActionMessageBoxDialog")
        ActionMessageBoxDialog.resize(500, 200)
        ActionMessageBoxDialog.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        ActionMessageBoxDialog.setFont(font)
        ActionMessageBoxDialog.setStyleSheet("QDialog {\n"
"    background-color: #FFFFFF; \n"
"}\n"
"\n"
"QLabel {\n"
"    color: #0F172A;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #FFFFFF;\n"
"    border: none;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ActionMessageBoxDialog)
        self.verticalLayout.setContentsMargins(16, 24, 16, 16)
        self.verticalLayout.setSpacing(24)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_frame = QtWidgets.QFrame(ActionMessageBoxDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_frame.sizePolicy().hasHeightForWidth())
        self.message_frame.setSizePolicy(sizePolicy)
        self.message_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.message_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.message_frame.setObjectName("message_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.message_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(36)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.message_icon_label = QtWidgets.QLabel(self.message_frame)
        self.message_icon_label.setMinimumSize(QtCore.QSize(64, 64))
        self.message_icon_label.setMaximumSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.message_icon_label.setFont(font)
        self.message_icon_label.setText("")
        self.message_icon_label.setObjectName("message_icon_label")
        self.horizontalLayout.addWidget(self.message_icon_label)
        self.text_frame = QtWidgets.QFrame(self.message_frame)
        self.text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_frame.setObjectName("text_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.text_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.message_text_label = QtWidgets.QLabel(self.text_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_text_label.sizePolicy().hasHeightForWidth())
        self.message_text_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.message_text_label.setFont(font)
        self.message_text_label.setWordWrap(True)
        self.message_text_label.setObjectName("message_text_label")
        self.horizontalLayout_3.addWidget(self.message_text_label)
        self.horizontalLayout.addWidget(self.text_frame)
        self.verticalLayout.addWidget(self.message_frame)
        self.buttons_frame = QtWidgets.QFrame(ActionMessageBoxDialog)
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttons_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(225, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.main_action_pushButton = QtWidgets.QPushButton(self.buttons_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_action_pushButton.sizePolicy().hasHeightForWidth())
        self.main_action_pushButton.setSizePolicy(sizePolicy)
        self.main_action_pushButton.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.main_action_pushButton.setFont(font)
        self.main_action_pushButton.setObjectName("main_action_pushButton")
        self.horizontalLayout_2.addWidget(self.main_action_pushButton)
        self.secondary_action_pushButton = QtWidgets.QPushButton(self.buttons_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.secondary_action_pushButton.sizePolicy().hasHeightForWidth())
        self.secondary_action_pushButton.setSizePolicy(sizePolicy)
        self.secondary_action_pushButton.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.secondary_action_pushButton.setFont(font)
        self.secondary_action_pushButton.setObjectName("secondary_action_pushButton")
        self.horizontalLayout_2.addWidget(self.secondary_action_pushButton)
        self.verticalLayout.addWidget(self.buttons_frame)

        self.retranslateUi(ActionMessageBoxDialog)
        QtCore.QMetaObject.connectSlotsByName(ActionMessageBoxDialog)

    def retranslateUi(self, ActionMessageBoxDialog):
        _translate = QtCore.QCoreApplication.translate
        ActionMessageBoxDialog.setWindowTitle(_translate("ActionMessageBoxDialog", "Dialog"))
        self.message_text_label.setText(_translate("ActionMessageBoxDialog", "TextLabel"))
        self.main_action_pushButton.setText(_translate("ActionMessageBoxDialog", "Текст"))
        self.secondary_action_pushButton.setText(_translate("ActionMessageBoxDialog", "Текст"))
