# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #FFFFFF;    /* Белый фон окна */\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #0F172A;   /* Акцентный цвет текста */\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #FFFFFF;\n"
"    border: none;\n"
"}\n"
"\n"
"/* === Горизонтальные линии === */\n"
"QFrame[frameShape=\"4\"] { /* QFrame::HLine */\n"
"    background-color: #E2E8F0;\n"
"    min-height: 1px;\n"
"    max-height: 1px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* === Вертикальные линии === */\n"
"QFrame[frameShape=\"5\"] { /* QFrame::VLine */\n"
"    background-color: #E2E8F0;\n"
"    min-width: 1px;\n"
"    max-width: 1px;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"\n"
"/* === Базовый стиль для всех QLineEdit === */\n"
"QLineEdit {\n"
"    background-color: #FFFFFF;       /* Белый фон */\n"
"    border: 1px solid #E2E8F0;       /* Светлая рамка */\n"
"    border-radius: 6px;              /* Скругления */\n"
"    color: #64748B;                  /* Цвет текста */\n"
"    padding: 6px 8px;                /* Внутренние отступы для аккуратности */\n"
"}\n"
"\n"
"/* === При фокусе (активное поле ввода) === */\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;       /* Белый фон */\n"
"    border: 1px solid #2563EB;       /* Синяя рамка */\n"
"    border-radius: 6px;\n"
"    color: #0F172A;                  /* Тёмный текст */\n"
"    outline: none;                   /* Убираем системный контур */\n"
"}\n"
"\n"
"/* === Отключенное состояние === */\n"
"QLineEdit:disabled {\n"
"    background-color: #FFFFFF;       /* Белый фон (не серый) */\n"
"    border: 1px solid #F8FAFC;       /* Очень светлая рамка */\n"
"    border-radius: 6px;\n"
"    color: #E2E8F0;                  /* Бледный текст */\n"
"}\n"
"\n"
"\n"
"/* === Второстепенные кнопки === */\n"
"QPushButton {\n"
"    background-color: transparent;   /* Без заливки */\n"
"    color: #334155;                  /* Основной цвет текста */\n"
"    font-weight: normal;             /* Обычная жирность */\n"
"    border: 1px solid #64748B;       /* Серо-синяя рамка */\n"
"    border-radius: 6px;              /* Скругления */\n"
"    padding: 6px 12px;               /* Внутренние отступы */\n"
"}\n"
"\n"
"/* === Наведение (hover) === */\n"
"QPushButton:hover {\n"
"    border: 1px solid #8B98AA;       /* Более светлая рамка */\n"
"}\n"
"\n"
"/* === Нажатие (pressed / checked) === */\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    border: 1px solid #515E71;       /* Более тёмная рамка */\n"
"}\n"
"\n"
"/* === Отключена (disabled) === */\n"
"QPushButton:disabled {\n"
"    color: #E2E8F0;                  /* Бледный текст */\n"
"    border: 1px solid #F8FAFC;       /* Светлая рамка */\n"
"}\n"
"\n"
"\n"
"\n"
"/* === Общий стиль выпадающих списков (QComboBox) === */\n"
"QComboBox {\n"
"    background-color: #FFFFFF;           /* Белый фон */\n"
"    border: 1px solid #E2E8F0;           /* Светлая рамка */\n"
"    border-radius: 6px;                  /* Скругления */\n"
"    padding: 4px 32px 4px 8px;           /* Отступы: справа место под иконку */\n"
"    color: #64748B;                      /* Цвет текста */\n"
"}\n"
"\n"
"/* === Иконка стрелки (ресурс combobox_arrow) === */\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/combobox_arrow);        /* Подключённая иконка */\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}\n"
"\n"
"/* === Позиция иконки справа === */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border: none;                        /* Без отдельной рамки */\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"/* === Фокус или раскрытое состояние === */\n"
"QComboBox:focus,\n"
"QComboBox:on {\n"
"    border: 1px solid #2563EB;           /* Синяя рамка */\n"
"    color: #0F172A;                      /* Тёмный текст */\n"
"}\n"
"\n"
"/* === Меняем цвет стрелки при фокусе === */\n"
"QComboBox:focus::down-arrow,\n"
"QComboBox:on::down-arrow {\n"
"    image: url(:/combobox_arrow);        /* Та же иконка, Qt не поддерживает перекраску напрямую */\n"
"}\n"
"\n"
"/* Если у тебя есть возможность использовать SVG — можно будет менять цвет через fill в ресурсе */\n"
"\n"
"/* === Отключённое состояние === */\n"
"QComboBox:disabled {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #F8FAFC;           /* Очень светлая рамка */\n"
"    color: #E2E8F0;                      /* Светлый текст */\n"
"}\n"
"\n"
"QComboBox:disabled::down-arrow {\n"
"    image: url(:/combobox_arrow);        /* Та же иконка */\n"
"    /* Qt не позволяет легко изменить цвет, поэтому сделай отдельный серый SVG для disabled */\n"
"}\n"
"\n"
"/* === Стиль выпадающего списка === */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFFFFF;           /* Белый фон меню */\n"
"    border: 1px solid #E2E8F0;           /* Та же рамка */\n"
"    border-radius: 6px;\n"
"    selection-background-color: #2563EB; /* Цвет выделения */\n"
"    selection-color: #FFFFFF;            /* Цвет текста при выделении */\n"
"}\n"
"\n"
"\n"
"\n"
"/* === Общие стили для QRadioButton === */\n"
"QRadioButton {\n"
"    color: #0F172A;            /* Акцентный текст */\n"
"    font-weight: normal;\n"
"    spacing: 8px;              /* Расстояние между индикатором и текстом */\n"
"}\n"
"\n"
"/* === Индикатор === */\n"
"QRadioButton::indicator {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}\n"
"\n"
"/* === Активное === */\n"
"QRadioButton::indicator:checked {\n"
"    image: url(:/icons/radio_buttons/radio_button_checked.svg);\n"
"}\n"
"\n"
"/* === Активное + наведение === */\n"
"QRadioButton::indicator:checked:hover {\n"
"    image: url(:/icons/radio_buttons/radio_button_checked_hover.svg);\n"
"}\n"
"\n"
"/* === Активное + нажатие === */\n"
"QRadioButton::indicator:checked:pressed {\n"
"    image: url(:/icons/radio_buttons/radio_button_checked_pressed.svg);\n"
"}\n"
"\n"
"/* === Активное Отключённое === */\n"
"QRadioButton::indicator:checked:disabled {\n"
"    image: url(:/icons/radio_buttons/radio_button_checked_disabled.svg);\n"
"}\n"
"\n"
"/* === Неактивное === */\n"
"QRadioButton::indicator:unchecked {\n"
"    image: url(:/icons/radio_buttons/radio_button_unchecked.svg);\n"
"}\n"
"\n"
"/* === Неактивное + наведение === */\n"
"QRadioButton::indicator:unchecked:hover {\n"
"    image: url(:/icons/radio_buttons/radio_button_unchecked_hover.svg);\n"
"}\n"
"\n"
"/* === Неактивное + нажатие === */\n"
"QRadioButton::indicator:unchecked:pressed {\n"
"    image: url(:/icons/radio_buttons/radio_button_unchecked_pressed.svg);\n"
"}\n"
"\n"
"/* === Неактивное Отключённое=== */\n"
"QRadioButton::indicator:unchecked:disabled {\n"
"    image: url(:/icons/radio_buttons/radio_button_unchecked_disabled.svg);\n"
"}\n"
"\n"
"/* === Текст отключённой радиокнопки === */\n"
"QRadioButton:disabled {\n"
"    color: #64748B;\n"
"}\n"
"\n"
"\n"
"\n"
"/* === Общие стили для QCheckBox === */\n"
"QCheckBox{\n"
"    color: #0F172A;                /* Акцентный текст */\n"
"    font-weight: normal;\n"
"    spacing: 8px;                  /* Расстояние между индикатором и текстом */\n"
"}\n"
"\n"
"/* Индикатор */\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    border-radius: 3px;            /* Небольшое скругление углов */\n"
"    border: 1px solid #64748B;     /* Второстепенная рамка */\n"
"    background-color: #FFFFFF;     /* Белый фон */\n"
"}\n"
"\n"
"/* Наведение */\n"
"QCheckBox::indicator:hover {\n"
"    border: 1px solid #2563EB;     /* Акцентная рамка */\n"
"}\n"
"\n"
"/* Активен (галочка) */\n"
"QCheckBox::indicator:checked {\n"
"    border: 1px solid #2563EB;\n"
"    background-color: #2563EB;\n"
"    image: url(:/icons/checkbox_check);  /* Собственная белая галочка */\n"
"}\n"
"\n"
"/* Фокус */\n"
"QCheckBox::indicator:focus {\n"
"    border: 1px solid #2563EB;\n"
"}\n"
"\n"
"/* Отключён */\n"
"QCheckBox::indicator:disabled {\n"
"    border: 1px solid #F8FAFC;\n"
"    background-color: #FFFFFF;\n"
"    image: none;\n"
"}\n"
"\n"
"/* Текст отключённого чекбокса */\n"
"QCheckBox:disabled {\n"
"    color: #64748B;\n"
"}\n"
"\n"
"\n"
"\n"
"/* === Общий стиль прогресс-бара === */\n"
"QProgressBar {\n"
"    border: 1px solid #E2E8F0;     /* Светлая рамка */\n"
"    border-radius: 6px;            /* Скругления */\n"
"    background-color: #FFFFFF;     /* Белый фон (без заполнения) */\n"
"    text-align: center;            /* На всякий случай, но текста нет */\n"
"    color: transparent;            /* Полностью скрываем текст */\n"
"}\n"
"\n"
"/* === Полоса заполнения === */\n"
"QProgressBar::chunk {\n"
"    border-radius: 6px;            /* Та же форма, чтобы совпадала с контуром */\n"
"    background-color: #16A34A;     /* Зелёный акцент */\n"
"    margin: 0px;                   /* Без промежутков между сегментами */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.navigation_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navigation_frame.sizePolicy().hasHeightForWidth())
        self.navigation_frame.setSizePolicy(sizePolicy)
        self.navigation_frame.setMinimumSize(QtCore.QSize(200, 0))
        self.navigation_frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.navigation_frame.setStyleSheet("/* === Обычные фреймы (панели, контейнеры) === */\n"
"QFrame {\n"
"    border: none;\n"
"    background-color: #F4F6F9; /* Цвет панелей */\n"
"}\n"
"\n"
"/* === Горизонтальные линии === */\n"
"QFrame[frameShape=\"4\"] { /* QFrame::HLine */\n"
"    background-color: #DDDDDD;\n"
"    min-height: 1px;\n"
"    max-height: 1px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* === Базовые свойства sidebar-кнопок === */\n"
"QPushButton#download_tab_pushButton,\n"
"QPushButton#add_tab_pushButton,\n"
"QPushButton#delete_tab_pushButton{\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 12px;\n"
"    text-align: left;                /* Текст и иконка выровнены слева */\n"
"    font-weight: normal;\n"
"    background-color: #DEE8FC;       /* Неактивное состояние по умолчанию */\n"
"    color: #0F172A;                  /* Тёмный текст */\n"
"    qproperty-iconSize: 24px 24px;\n"
"}\n"
"\n"
"/* === Наведение === */\n"
"QPushButton#download_tab_pushButton:hover,\n"
"QPushButton#add_tab_pushButton:hover,\n"
"QPushButton#delete_tab_pushButton:hover{\n"
"    background-color: #C8D9FF;       /* Светло-синий hover */\n"
"}\n"
"\n"
"/* === Активная (нажатая / выбранная / залипшая) кнопка === */\n"
"QPushButton#download_tab_pushButton:checked,\n"
"QPushButton#add_tab_pushButton:checked,\n"
"QPushButton#delete_tab_pushButton:checked{\n"
"    background-color: #2563EB;       /* Акцентный синий фон */\n"
"    color: #FFFFFF;                  /* Белый текст */\n"
"    font-weight: bold;               /* Жирный шрифт */\n"
"}\n"
"\n"
"/* === Неактивная иконка === */\n"
"QPushButton#download_tab_pushButton:checked::icon,\n"
"QPushButton#add_tab_pushButton:checked::icon,\n"
"QPushButton#delete_tab_pushButton:checked::icon{\n"
"    color: #2563EB;                  /* Синяя иконка для неактивного состояния */\n"
"}\n"
"\n"
"/* === Активная иконка === */\n"
"QPushButton#download_tab_pushButton:checked::icon,\n"
"QPushButton#add_tab_pushButton:checked::icon,\n"
"QPushButton#delete_tab_pushButton:checked::icon{\n"
"    color: #FFFFFF;                  /* Белая иконка при активной кнопке */\n"
"}\n"
"\n"
"/* === Наведение при активной кнопке (мягкое осветление) === */\n"
"QPushButton#download_tab_pushButton:checked:hover,\n"
"QPushButton#add_tab_pushButton:checke:hoverd,\n"
"QPushButton#delete_tab_pushButton:checked:hover{\n"
"    background-color: #3B76F6;       /* Чуть светлее активного синего */\n"
"}")
        self.navigation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navigation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navigation_frame.setObjectName("navigation_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.navigation_frame)
        self.verticalLayout_2.setContentsMargins(8, 16, 8, 16)
        self.verticalLayout_2.setSpacing(24)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo_label = QtWidgets.QLabel(self.navigation_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label.sizePolicy().hasHeightForWidth())
        self.logo_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.logo_label.setFont(font)
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_2.addWidget(self.logo_label)
        self.line = QtWidgets.QFrame(self.navigation_frame)
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.buttons_frame = QtWidgets.QFrame(self.navigation_frame)
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.buttons_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.download_tab_pushButton = QtWidgets.QPushButton(self.buttons_frame)
        self.download_tab_pushButton.setMinimumSize(QtCore.QSize(0, 48))
        self.download_tab_pushButton.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.download_tab_pushButton.setFont(font)
        self.download_tab_pushButton.setCheckable(True)
        self.download_tab_pushButton.setChecked(True)
        self.download_tab_pushButton.setAutoRepeat(False)
        self.download_tab_pushButton.setAutoExclusive(True)
        self.download_tab_pushButton.setObjectName("download_tab_pushButton")
        self.verticalLayout.addWidget(self.download_tab_pushButton)
        self.add_tab_pushButton = QtWidgets.QPushButton(self.buttons_frame)
        self.add_tab_pushButton.setMinimumSize(QtCore.QSize(0, 48))
        self.add_tab_pushButton.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.add_tab_pushButton.setFont(font)
        self.add_tab_pushButton.setCheckable(True)
        self.add_tab_pushButton.setAutoExclusive(True)
        self.add_tab_pushButton.setObjectName("add_tab_pushButton")
        self.verticalLayout.addWidget(self.add_tab_pushButton)
        self.delete_tab_pushButton = QtWidgets.QPushButton(self.buttons_frame)
        self.delete_tab_pushButton.setMinimumSize(QtCore.QSize(0, 48))
        self.delete_tab_pushButton.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.delete_tab_pushButton.setFont(font)
        self.delete_tab_pushButton.setCheckable(True)
        self.delete_tab_pushButton.setAutoExclusive(True)
        self.delete_tab_pushButton.setObjectName("delete_tab_pushButton")
        self.verticalLayout.addWidget(self.delete_tab_pushButton)
        self.verticalLayout_2.addWidget(self.buttons_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 341, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.version_label = QtWidgets.QLabel(self.navigation_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.version_label.setFont(font)
        self.version_label.setStyleSheet("QLabel{\n"
"    color: #DDDDDD;\n"
"}")
        self.version_label.setAlignment(QtCore.Qt.AlignCenter)
        self.version_label.setObjectName("version_label")
        self.verticalLayout_2.addWidget(self.version_label)
        self.horizontalLayout.addWidget(self.navigation_frame)
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.main_frame.setFont(font)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabs_stackedWidget = QtWidgets.QStackedWidget(self.main_frame)
        self.tabs_stackedWidget.setStyleSheet("")
        self.tabs_stackedWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tabs_stackedWidget.setLineWidth(1)
        self.tabs_stackedWidget.setObjectName("tabs_stackedWidget")
        self.download_page = QtWidgets.QWidget()
        self.download_page.setObjectName("download_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.download_page)
        self.verticalLayout_7.setContentsMargins(8, 16, 8, 16)
        self.verticalLayout_7.setSpacing(16)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.filters_frame = QtWidgets.QFrame(self.download_page)
        self.filters_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filters_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filters_frame.setObjectName("filters_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.filters_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.search_frame = QtWidgets.QFrame(self.filters_frame)
        self.search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_frame.setObjectName("search_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.search_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_label = QtWidgets.QLabel(self.search_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_label.sizePolicy().hasHeightForWidth())
        self.search_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.search_label.setFont(font)
        self.search_label.setObjectName("search_label")
        self.horizontalLayout_3.addWidget(self.search_label)
        self.search_lineEdit = QtWidgets.QLineEdit(self.search_frame)
        self.search_lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.search_lineEdit.setFont(font)
        self.search_lineEdit.setStyleSheet("")
        self.search_lineEdit.setText("")
        self.search_lineEdit.setFrame(True)
        self.search_lineEdit.setClearButtonEnabled(True)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.horizontalLayout_3.addWidget(self.search_lineEdit)
        self.verticalLayout_5.addWidget(self.search_frame)
        self.checkBox = QtWidgets.QCheckBox(self.filters_frame)
        self.checkBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_5.addWidget(self.checkBox)
        self.verticalLayout_7.addWidget(self.filters_frame)
        self.tableWidget = QtWidgets.QTableWidget(self.download_page)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.tableWidget)
        self.choose_file_frame = QtWidgets.QFrame(self.download_page)
        self.choose_file_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choose_file_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_file_frame.setObjectName("choose_file_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.choose_file_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.choose_file_label = QtWidgets.QLabel(self.choose_file_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_file_label.sizePolicy().hasHeightForWidth())
        self.choose_file_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_file_label.setFont(font)
        self.choose_file_label.setObjectName("choose_file_label")
        self.horizontalLayout_4.addWidget(self.choose_file_label)
        spacerItem1 = QtWidgets.QSpacerItem(604, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.back_pushButton = QtWidgets.QPushButton(self.choose_file_frame)
        self.back_pushButton.setEnabled(False)
        self.back_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.back_pushButton.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.back_pushButton.setFont(font)
        self.back_pushButton.setObjectName("back_pushButton")
        self.horizontalLayout_4.addWidget(self.back_pushButton)
        self.verticalLayout_7.addWidget(self.choose_file_frame)
        self.line_2 = QtWidgets.QFrame(self.download_page)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.save_fil_path_frame = QtWidgets.QFrame(self.download_page)
        self.save_fil_path_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.save_fil_path_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.save_fil_path_frame.setObjectName("save_fil_path_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.save_fil_path_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.save_fil_path_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.save_file_path_actions_frame = QtWidgets.QFrame(self.save_fil_path_frame)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        self.save_file_path_actions_frame.setFont(font)
        self.save_file_path_actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.save_file_path_actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.save_file_path_actions_frame.setObjectName("save_file_path_actions_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.save_file_path_actions_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.save_file_path_lineEdit = QtWidgets.QLineEdit(self.save_file_path_actions_frame)
        self.save_file_path_lineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.save_file_path_lineEdit.setFont(font)
        self.save_file_path_lineEdit.setClearButtonEnabled(True)
        self.save_file_path_lineEdit.setObjectName("save_file_path_lineEdit")
        self.horizontalLayout_5.addWidget(self.save_file_path_lineEdit)
        self.save_file_path_choose_pushButton = QtWidgets.QPushButton(self.save_file_path_actions_frame)
        self.save_file_path_choose_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.save_file_path_choose_pushButton.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.save_file_path_choose_pushButton.setFont(font)
        self.save_file_path_choose_pushButton.setObjectName("save_file_path_choose_pushButton")
        self.horizontalLayout_5.addWidget(self.save_file_path_choose_pushButton)
        self.verticalLayout_6.addWidget(self.save_file_path_actions_frame)
        self.verticalLayout_7.addWidget(self.save_fil_path_frame)
        self.download_file_pushButton = QtWidgets.QPushButton(self.download_page)
        self.download_file_pushButton.setEnabled(False)
        self.download_file_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.download_file_pushButton.setFont(font)
        self.download_file_pushButton.setStyleSheet("/* === Акцентная кнопка=== */\n"
"QPushButton {\n"
"    background-color: #2563EB;       /* Основной синий */\n"
"    color: #FFFFFF;                  /* Белый текст */\n"
"    font-weight: bold;               /* Жирный шрифт */\n"
"    border: none;                    /* Без рамки */\n"
"    border-radius: 6px;              /* Скругления */\n"
"    padding: 6px 12px;               /* Отступы для аккуратности */\n"
"}\n"
"\n"
"/* === Наведение (hover) === */\n"
"QPushButton:hover {\n"
"    background-color: #5283EF;       /* Более светлый синий */\n"
"}\n"
"\n"
"/* === Нажатие (pressed / checked) === */\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background-color: #124CC9;       /* Тёмно-синий при клике */\n"
"}\n"
"\n"
"/* === Отключена (disabled) === */\n"
"QPushButton:disabled {\n"
"    background-color: #DEE8FC;       /* Бледно-синий фон */\n"
"    color: #FFFFFF;                  /* Белый текст (можно осветлить при желании) */\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.download_file_pushButton.setObjectName("download_file_pushButton")
        self.verticalLayout_7.addWidget(self.download_file_pushButton)
        self.tabs_stackedWidget.addWidget(self.download_page)
        self.add_page = QtWidgets.QWidget()
        self.add_page.setObjectName("add_page")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.add_page)
        self.verticalLayout_13.setContentsMargins(8, 16, 8, 16)
        self.verticalLayout_13.setSpacing(16)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.choose_or_create_frame = QtWidgets.QFrame(self.add_page)
        self.choose_or_create_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choose_or_create_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_or_create_frame.setObjectName("choose_or_create_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.choose_or_create_frame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.choose_or_create_label = QtWidgets.QLabel(self.choose_or_create_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.choose_or_create_label.setFont(font)
        self.choose_or_create_label.setObjectName("choose_or_create_label")
        self.verticalLayout_8.addWidget(self.choose_or_create_label)
        self.choose_or_create_actions_frame = QtWidgets.QFrame(self.choose_or_create_frame)
        self.choose_or_create_actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choose_or_create_actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_or_create_actions_frame.setObjectName("choose_or_create_actions_frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.choose_or_create_actions_frame)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(16)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groups_comboBox = QtWidgets.QComboBox(self.choose_or_create_actions_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groups_comboBox.sizePolicy().hasHeightForWidth())
        self.groups_comboBox.setSizePolicy(sizePolicy)
        self.groups_comboBox.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.groups_comboBox.setFont(font)
        self.groups_comboBox.setObjectName("groups_comboBox")
        self.horizontalLayout_12.addWidget(self.groups_comboBox)
        self.line_3 = QtWidgets.QFrame(self.choose_or_create_actions_frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_12.addWidget(self.line_3)
        self.create_group_actions_frame = QtWidgets.QFrame(self.choose_or_create_actions_frame)
        self.create_group_actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.create_group_actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.create_group_actions_frame.setObjectName("create_group_actions_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.create_group_actions_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.group_name_lineEdit = QtWidgets.QLineEdit(self.create_group_actions_frame)
        self.group_name_lineEdit.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.group_name_lineEdit.setFont(font)
        self.group_name_lineEdit.setClearButtonEnabled(True)
        self.group_name_lineEdit.setObjectName("group_name_lineEdit")
        self.horizontalLayout_6.addWidget(self.group_name_lineEdit)
        self.create_group_pushButton = QtWidgets.QPushButton(self.create_group_actions_frame)
        self.create_group_pushButton.setEnabled(False)
        self.create_group_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.create_group_pushButton.setFont(font)
        self.create_group_pushButton.setObjectName("create_group_pushButton")
        self.horizontalLayout_6.addWidget(self.create_group_pushButton)
        self.horizontalLayout_12.addWidget(self.create_group_actions_frame)
        self.verticalLayout_8.addWidget(self.choose_or_create_actions_frame)
        self.verticalLayout_13.addWidget(self.choose_or_create_frame)
        self.select_add_format_frame = QtWidgets.QFrame(self.add_page)
        self.select_add_format_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.select_add_format_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.select_add_format_frame.setObjectName("select_add_format_frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.select_add_format_frame)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(16)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.selecet_format_frame = QtWidgets.QFrame(self.select_add_format_frame)
        self.selecet_format_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selecet_format_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selecet_format_frame.setObjectName("selecet_format_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.selecet_format_frame)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.select_type_label = QtWidgets.QLabel(self.selecet_format_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_type_label.sizePolicy().hasHeightForWidth())
        self.select_type_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.select_type_label.setFont(font)
        self.select_type_label.setObjectName("select_type_label")
        self.verticalLayout_11.addWidget(self.select_type_label)
        self.select_add_format_actions_frame = QtWidgets.QFrame(self.selecet_format_frame)
        self.select_add_format_actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.select_add_format_actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.select_add_format_actions_frame.setObjectName("select_add_format_actions_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.select_add_format_actions_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(16)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.version_radioButton = QtWidgets.QRadioButton(self.select_add_format_actions_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.version_radioButton.sizePolicy().hasHeightForWidth())
        self.version_radioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.version_radioButton.setFont(font)
        self.version_radioButton.setChecked(True)
        self.version_radioButton.setObjectName("version_radioButton")
        self.horizontalLayout_8.addWidget(self.version_radioButton)
        self.instruction_radioButton = QtWidgets.QRadioButton(self.select_add_format_actions_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instruction_radioButton.sizePolicy().hasHeightForWidth())
        self.instruction_radioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.instruction_radioButton.setFont(font)
        self.instruction_radioButton.setObjectName("instruction_radioButton")
        self.horizontalLayout_8.addWidget(self.instruction_radioButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_11.addWidget(self.select_add_format_actions_frame)
        self.verticalLayout_12.addWidget(self.selecet_format_frame)
        self.add_format_stackedWidget = QtWidgets.QStackedWidget(self.select_add_format_frame)
        self.add_format_stackedWidget.setObjectName("add_format_stackedWidget")
        self.version_page = QtWidgets.QWidget()
        self.version_page.setObjectName("version_page")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.version_page)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(16)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.choose_version_folder_label = QtWidgets.QLabel(self.version_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_version_folder_label.sizePolicy().hasHeightForWidth())
        self.choose_version_folder_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_version_folder_label.setFont(font)
        self.choose_version_folder_label.setObjectName("choose_version_folder_label")
        self.verticalLayout_14.addWidget(self.choose_version_folder_label)
        self.choose_version_folder_frame = QtWidgets.QFrame(self.version_page)
        self.choose_version_folder_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choose_version_folder_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_version_folder_frame.setObjectName("choose_version_folder_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.choose_version_folder_frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.choose_version_folder_lineEdit = QtWidgets.QLineEdit(self.choose_version_folder_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_version_folder_lineEdit.setFont(font)
        self.choose_version_folder_lineEdit.setClearButtonEnabled(True)
        self.choose_version_folder_lineEdit.setObjectName("choose_version_folder_lineEdit")
        self.horizontalLayout_9.addWidget(self.choose_version_folder_lineEdit)
        self.choose_version_folder_pushButton = QtWidgets.QPushButton(self.choose_version_folder_frame)
        self.choose_version_folder_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_version_folder_pushButton.setFont(font)
        self.choose_version_folder_pushButton.setObjectName("choose_version_folder_pushButton")
        self.horizontalLayout_9.addWidget(self.choose_version_folder_pushButton)
        self.verticalLayout_14.addWidget(self.choose_version_folder_frame)
        self.add_version_pushButton = QtWidgets.QPushButton(self.version_page)
        self.add_version_pushButton.setEnabled(False)
        self.add_version_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_version_pushButton.setFont(font)
        self.add_version_pushButton.setStyleSheet("/* === Акцентная кнопка=== */\n"
"QPushButton {\n"
"    background-color: #2563EB;       /* Основной синий */\n"
"    color: #FFFFFF;                  /* Белый текст */\n"
"    font-weight: bold;               /* Жирный шрифт */\n"
"    border: none;                    /* Без рамки */\n"
"    border-radius: 6px;              /* Скругления */\n"
"    padding: 6px 12px;               /* Отступы для аккуратности */\n"
"}\n"
"\n"
"/* === Наведение (hover) === */\n"
"QPushButton:hover {\n"
"    background-color: #5283EF;       /* Более светлый синий */\n"
"}\n"
"\n"
"/* === Нажатие (pressed / checked) === */\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background-color: #124CC9;       /* Тёмно-синий при клике */\n"
"}\n"
"\n"
"/* === Отключена (disabled) === */\n"
"QPushButton:disabled {\n"
"    background-color: #DEE8FC;       /* Бледно-синий фон */\n"
"    color: #FFFFFF;                  /* Белый текст (можно осветлить при желании) */\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.add_version_pushButton.setObjectName("add_version_pushButton")
        self.verticalLayout_14.addWidget(self.add_version_pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem3)
        self.add_format_stackedWidget.addWidget(self.version_page)
        self.instruction_page = QtWidgets.QWidget()
        self.instruction_page.setObjectName("instruction_page")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.instruction_page)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(16)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.choose_instruction_file_label = QtWidgets.QLabel(self.instruction_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_instruction_file_label.sizePolicy().hasHeightForWidth())
        self.choose_instruction_file_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_instruction_file_label.setFont(font)
        self.choose_instruction_file_label.setObjectName("choose_instruction_file_label")
        self.verticalLayout_15.addWidget(self.choose_instruction_file_label)
        self.choose_instruction_file_frame = QtWidgets.QFrame(self.instruction_page)
        self.choose_instruction_file_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choose_instruction_file_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_instruction_file_frame.setObjectName("choose_instruction_file_frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.choose_instruction_file_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(8)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.choose_instruction_file_lineEdit = QtWidgets.QLineEdit(self.choose_instruction_file_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_instruction_file_lineEdit.setFont(font)
        self.choose_instruction_file_lineEdit.setClearButtonEnabled(True)
        self.choose_instruction_file_lineEdit.setObjectName("choose_instruction_file_lineEdit")
        self.horizontalLayout_10.addWidget(self.choose_instruction_file_lineEdit)
        self.choose_instruction_file_pushButton = QtWidgets.QPushButton(self.choose_instruction_file_frame)
        self.choose_instruction_file_pushButton.setEnabled(True)
        self.choose_instruction_file_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_instruction_file_pushButton.setFont(font)
        self.choose_instruction_file_pushButton.setObjectName("choose_instruction_file_pushButton")
        self.horizontalLayout_10.addWidget(self.choose_instruction_file_pushButton)
        self.verticalLayout_15.addWidget(self.choose_instruction_file_frame)
        self.add_instruction_pushButton = QtWidgets.QPushButton(self.instruction_page)
        self.add_instruction_pushButton.setEnabled(False)
        self.add_instruction_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_instruction_pushButton.setFont(font)
        self.add_instruction_pushButton.setStyleSheet("/* === Акцентная кнопка=== */\n"
"QPushButton {\n"
"    background-color: #2563EB;       /* Основной синий */\n"
"    color: #FFFFFF;                  /* Белый текст */\n"
"    font-weight: bold;               /* Жирный шрифт */\n"
"    border: none;                    /* Без рамки */\n"
"    border-radius: 6px;              /* Скругления */\n"
"    padding: 6px 12px;               /* Отступы для аккуратности */\n"
"}\n"
"\n"
"/* === Наведение (hover) === */\n"
"QPushButton:hover {\n"
"    background-color: #5283EF;       /* Более светлый синий */\n"
"}\n"
"\n"
"/* === Нажатие (pressed / checked) === */\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background-color: #124CC9;       /* Тёмно-синий при клике */\n"
"}\n"
"\n"
"/* === Отключена (disabled) === */\n"
"QPushButton:disabled {\n"
"    background-color: #DEE8FC;       /* Бледно-синий фон */\n"
"    color: #FFFFFF;                  /* Белый текст (можно осветлить при желании) */\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.add_instruction_pushButton.setObjectName("add_instruction_pushButton")
        self.verticalLayout_15.addWidget(self.add_instruction_pushButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem4)
        self.add_format_stackedWidget.addWidget(self.instruction_page)
        self.verticalLayout_12.addWidget(self.add_format_stackedWidget)
        self.verticalLayout_13.addWidget(self.select_add_format_frame)
        self.tabs_stackedWidget.addWidget(self.add_page)
        self.delete_page = QtWidgets.QWidget()
        self.delete_page.setObjectName("delete_page")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.delete_page)
        self.verticalLayout_17.setContentsMargins(8, 16, 8, 16)
        self.verticalLayout_17.setSpacing(16)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.what_delete_frame = QtWidgets.QFrame(self.delete_page)
        self.what_delete_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.what_delete_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.what_delete_frame.setObjectName("what_delete_frame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.what_delete_frame)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(8)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.what_delete_label = QtWidgets.QLabel(self.what_delete_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.what_delete_label.sizePolicy().hasHeightForWidth())
        self.what_delete_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.what_delete_label.setFont(font)
        self.what_delete_label.setObjectName("what_delete_label")
        self.verticalLayout_16.addWidget(self.what_delete_label)
        self.what_delete_actions_frame = QtWidgets.QFrame(self.what_delete_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.what_delete_actions_frame.sizePolicy().hasHeightForWidth())
        self.what_delete_actions_frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.what_delete_actions_frame.setFont(font)
        self.what_delete_actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.what_delete_actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.what_delete_actions_frame.setObjectName("what_delete_actions_frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.what_delete_actions_frame)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(16)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.what_delete_file_radioButton = QtWidgets.QRadioButton(self.what_delete_actions_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.what_delete_file_radioButton.setFont(font)
        self.what_delete_file_radioButton.setChecked(True)
        self.what_delete_file_radioButton.setObjectName("what_delete_file_radioButton")
        self.horizontalLayout_11.addWidget(self.what_delete_file_radioButton)
        self.what_delete_group_radioButton = QtWidgets.QRadioButton(self.what_delete_actions_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.what_delete_group_radioButton.setFont(font)
        self.what_delete_group_radioButton.setObjectName("what_delete_group_radioButton")
        self.horizontalLayout_11.addWidget(self.what_delete_group_radioButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.verticalLayout_16.addWidget(self.what_delete_actions_frame)
        self.verticalLayout_17.addWidget(self.what_delete_frame)
        self.delete_stackedWidget = QtWidgets.QStackedWidget(self.delete_page)
        self.delete_stackedWidget.setObjectName("delete_stackedWidget")
        self.delete_file_page = QtWidgets.QWidget()
        self.delete_file_page.setObjectName("delete_file_page")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.delete_file_page)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(16)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.choose_group_to_delete_frame = QtWidgets.QFrame(self.delete_file_page)
        self.choose_group_to_delete_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choose_group_to_delete_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_group_to_delete_frame.setObjectName("choose_group_to_delete_frame")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.choose_group_to_delete_frame)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(8)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.choose_group_to_delete_label = QtWidgets.QLabel(self.choose_group_to_delete_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_group_to_delete_label.sizePolicy().hasHeightForWidth())
        self.choose_group_to_delete_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_group_to_delete_label.setFont(font)
        self.choose_group_to_delete_label.setObjectName("choose_group_to_delete_label")
        self.verticalLayout_19.addWidget(self.choose_group_to_delete_label)
        self.choose_group_to_delete_comboBox = QtWidgets.QComboBox(self.choose_group_to_delete_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_group_to_delete_comboBox.setFont(font)
        self.choose_group_to_delete_comboBox.setObjectName("choose_group_to_delete_comboBox")
        self.verticalLayout_19.addWidget(self.choose_group_to_delete_comboBox)
        self.verticalLayout_20.addWidget(self.choose_group_to_delete_frame)
        self.choose_file_to_delete_frame = QtWidgets.QFrame(self.delete_file_page)
        self.choose_file_to_delete_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choose_file_to_delete_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_file_to_delete_frame.setObjectName("choose_file_to_delete_frame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.choose_file_to_delete_frame)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(8)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.choose_file_to_delete_label = QtWidgets.QLabel(self.choose_file_to_delete_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_file_to_delete_label.sizePolicy().hasHeightForWidth())
        self.choose_file_to_delete_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_file_to_delete_label.setFont(font)
        self.choose_file_to_delete_label.setObjectName("choose_file_to_delete_label")
        self.verticalLayout_18.addWidget(self.choose_file_to_delete_label)
        self.choose_file_to_delete_comboBox = QtWidgets.QComboBox(self.choose_file_to_delete_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_file_to_delete_comboBox.setFont(font)
        self.choose_file_to_delete_comboBox.setObjectName("choose_file_to_delete_comboBox")
        self.verticalLayout_18.addWidget(self.choose_file_to_delete_comboBox)
        self.verticalLayout_20.addWidget(self.choose_file_to_delete_frame)
        self.accept_file_delete_checkBox = QtWidgets.QCheckBox(self.delete_file_page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.accept_file_delete_checkBox.setFont(font)
        self.accept_file_delete_checkBox.setObjectName("accept_file_delete_checkBox")
        self.verticalLayout_20.addWidget(self.accept_file_delete_checkBox)
        self.delete_file_pushButton = QtWidgets.QPushButton(self.delete_file_page)
        self.delete_file_pushButton.setEnabled(False)
        self.delete_file_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.delete_file_pushButton.setFont(font)
        self.delete_file_pushButton.setStyleSheet("/* === Акцентная кнопка=== */\n"
"QPushButton {\n"
"    background-color: #2563EB;       /* Основной синий */\n"
"    color: #FFFFFF;                  /* Белый текст */\n"
"    font-weight: bold;               /* Жирный шрифт */\n"
"    border: none;                    /* Без рамки */\n"
"    border-radius: 6px;              /* Скругления */\n"
"    padding: 6px 12px;               /* Отступы для аккуратности */\n"
"}\n"
"\n"
"/* === Наведение (hover) === */\n"
"QPushButton:hover {\n"
"    background-color: #5283EF;       /* Более светлый синий */\n"
"}\n"
"\n"
"/* === Нажатие (pressed / checked) === */\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background-color: #124CC9;       /* Тёмно-синий при клике */\n"
"}\n"
"\n"
"/* === Отключена (disabled) === */\n"
"QPushButton:disabled {\n"
"    background-color: #DEE8FC;       /* Бледно-синий фон */\n"
"    color: #FFFFFF;                  /* Белый текст (можно осветлить при желании) */\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.delete_file_pushButton.setObjectName("delete_file_pushButton")
        self.verticalLayout_20.addWidget(self.delete_file_pushButton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 283, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem6)
        self.delete_stackedWidget.addWidget(self.delete_file_page)
        self.delete_group_page = QtWidgets.QWidget()
        self.delete_group_page.setObjectName("delete_group_page")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.delete_group_page)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(16)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.choose_group_to_delete_frame_2 = QtWidgets.QFrame(self.delete_group_page)
        self.choose_group_to_delete_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.choose_group_to_delete_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.choose_group_to_delete_frame_2.setObjectName("choose_group_to_delete_frame_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.choose_group_to_delete_frame_2)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(8)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.choose_group_to_delete_label_2 = QtWidgets.QLabel(self.choose_group_to_delete_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_group_to_delete_label_2.sizePolicy().hasHeightForWidth())
        self.choose_group_to_delete_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_group_to_delete_label_2.setFont(font)
        self.choose_group_to_delete_label_2.setObjectName("choose_group_to_delete_label_2")
        self.verticalLayout_21.addWidget(self.choose_group_to_delete_label_2)
        self.choose_group_to_delete_comboBox_2 = QtWidgets.QComboBox(self.choose_group_to_delete_frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.choose_group_to_delete_comboBox_2.setFont(font)
        self.choose_group_to_delete_comboBox_2.setObjectName("choose_group_to_delete_comboBox_2")
        self.verticalLayout_21.addWidget(self.choose_group_to_delete_comboBox_2)
        self.verticalLayout_22.addWidget(self.choose_group_to_delete_frame_2)
        self.accept_group_delete_checkBox = QtWidgets.QCheckBox(self.delete_group_page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.accept_group_delete_checkBox.setFont(font)
        self.accept_group_delete_checkBox.setObjectName("accept_group_delete_checkBox")
        self.verticalLayout_22.addWidget(self.accept_group_delete_checkBox)
        self.delete_group_pushButton = QtWidgets.QPushButton(self.delete_group_page)
        self.delete_group_pushButton.setEnabled(False)
        self.delete_group_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.delete_group_pushButton.setFont(font)
        self.delete_group_pushButton.setStyleSheet("/* === Акцентная кнопка=== */\n"
"QPushButton {\n"
"    background-color: #2563EB;       /* Основной синий */\n"
"    color: #FFFFFF;                  /* Белый текст */\n"
"    font-weight: bold;               /* Жирный шрифт */\n"
"    border: none;                    /* Без рамки */\n"
"    border-radius: 6px;              /* Скругления */\n"
"    padding: 6px 12px;               /* Отступы для аккуратности */\n"
"}\n"
"\n"
"/* === Наведение (hover) === */\n"
"QPushButton:hover {\n"
"    background-color: #5283EF;       /* Более светлый синий */\n"
"}\n"
"\n"
"/* === Нажатие (pressed / checked) === */\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background-color: #124CC9;       /* Тёмно-синий при клике */\n"
"}\n"
"\n"
"/* === Отключена (disabled) === */\n"
"QPushButton:disabled {\n"
"    background-color: #DEE8FC;       /* Бледно-синий фон */\n"
"    color: #FFFFFF;                  /* Белый текст (можно осветлить при желании) */\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.delete_group_pushButton.setObjectName("delete_group_pushButton")
        self.verticalLayout_22.addWidget(self.delete_group_pushButton)
        spacerItem7 = QtWidgets.QSpacerItem(20, 361, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem7)
        self.delete_stackedWidget.addWidget(self.delete_group_page)
        self.verticalLayout_17.addWidget(self.delete_stackedWidget)
        self.tabs_stackedWidget.addWidget(self.delete_page)
        self.verticalLayout_4.addWidget(self.tabs_stackedWidget)
        self.progress_bar_frame = QtWidgets.QFrame(self.main_frame)
        self.progress_bar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_bar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_bar_frame.setObjectName("progress_bar_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.progress_bar_frame)
        self.verticalLayout_3.setContentsMargins(8, 0, 8, 16)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.progress_bar_labels_frame = QtWidgets.QFrame(self.progress_bar_frame)
        self.progress_bar_labels_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_bar_labels_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_bar_labels_frame.setObjectName("progress_bar_labels_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.progress_bar_labels_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.process_label = QtWidgets.QLabel(self.progress_bar_labels_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.process_label.setFont(font)
        self.process_label.setObjectName("process_label")
        self.horizontalLayout_2.addWidget(self.process_label)
        spacerItem8 = QtWidgets.QSpacerItem(683, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.percent_label = QtWidgets.QLabel(self.progress_bar_labels_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.percent_label.setFont(font)
        self.percent_label.setObjectName("percent_label")
        self.horizontalLayout_2.addWidget(self.percent_label)
        self.verticalLayout_3.addWidget(self.progress_bar_labels_frame)
        self.progressBar = QtWidgets.QProgressBar(self.progress_bar_frame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_4.addWidget(self.progress_bar_frame)
        self.horizontalLayout.addWidget(self.main_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs_stackedWidget.setCurrentIndex(0)
        self.add_format_stackedWidget.setCurrentIndex(0)
        self.delete_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "File Archive"))
        self.logo_label.setText(_translate("MainWindow", "File Archive"))
        self.download_tab_pushButton.setText(_translate("MainWindow", " Скачать"))
        self.add_tab_pushButton.setText(_translate("MainWindow", " Добавить"))
        self.delete_tab_pushButton.setText(_translate("MainWindow", " Удалить"))
        self.version_label.setText(_translate("MainWindow", "Version 4.0.0"))
        self.search_label.setText(_translate("MainWindow", "Поиск:"))
        self.search_lineEdit.setPlaceholderText(_translate("MainWindow", "Версия 1.0.2"))
        self.checkBox.setText(_translate("MainWindow", "Поиск всех версий"))
        self.choose_file_label.setText(_translate("MainWindow", "Выбран файл:"))
        self.back_pushButton.setText(_translate("MainWindow", "Назад"))
        self.label.setText(_translate("MainWindow", "Выберите папку для сохранения файла:"))
        self.save_file_path_lineEdit.setPlaceholderText(_translate("MainWindow", "По умолчанию файл будет сохранён на рабочем столе"))
        self.save_file_path_choose_pushButton.setText(_translate("MainWindow", "Выбрать"))
        self.download_file_pushButton.setText(_translate("MainWindow", "Скачать"))
        self.choose_or_create_label.setText(_translate("MainWindow", "Выберите группу или создайте новую:"))
        self.group_name_lineEdit.setPlaceholderText(_translate("MainWindow", "БВВ.01"))
        self.create_group_pushButton.setText(_translate("MainWindow", "Создать"))
        self.select_type_label.setText(_translate("MainWindow", "Выберите что хотите добавить:"))
        self.version_radioButton.setText(_translate("MainWindow", "Версия"))
        self.instruction_radioButton.setText(_translate("MainWindow", "Инструкция"))
        self.choose_version_folder_label.setText(_translate("MainWindow", "Выберите папку или вставьте путь к ней:"))
        self.choose_version_folder_lineEdit.setPlaceholderText(_translate("MainWindow", "C:\\"))
        self.choose_version_folder_pushButton.setText(_translate("MainWindow", "Выбрать"))
        self.add_version_pushButton.setText(_translate("MainWindow", "Добавить"))
        self.choose_instruction_file_label.setText(_translate("MainWindow", "Выберите файл или вставьте путь к нему:"))
        self.choose_instruction_file_lineEdit.setPlaceholderText(_translate("MainWindow", "C:\\"))
        self.choose_instruction_file_pushButton.setText(_translate("MainWindow", "Выбрать"))
        self.add_instruction_pushButton.setText(_translate("MainWindow", "Добавить"))
        self.what_delete_label.setText(_translate("MainWindow", "Выберите что хотите удалить:"))
        self.what_delete_file_radioButton.setText(_translate("MainWindow", "Файл"))
        self.what_delete_group_radioButton.setText(_translate("MainWindow", "Группу"))
        self.choose_group_to_delete_label.setText(_translate("MainWindow", "Выберите группу:"))
        self.choose_file_to_delete_label.setText(_translate("MainWindow", "Выберите файл:"))
        self.accept_file_delete_checkBox.setText(_translate("MainWindow", "Подтвердить удаление"))
        self.delete_file_pushButton.setText(_translate("MainWindow", "Удалить"))
        self.choose_group_to_delete_label_2.setText(_translate("MainWindow", "Выберите группу:"))
        self.accept_group_delete_checkBox.setText(_translate("MainWindow", "Подтвердить удаление"))
        self.delete_group_pushButton.setText(_translate("MainWindow", "Удалить"))
        self.process_label.setText(_translate("MainWindow", "Процесс..."))
        self.percent_label.setText(_translate("MainWindow", "0%"))
