# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/message_boxUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageBoxDialog(object):
    def setupUi(self, MessageBoxDialog):
        MessageBoxDialog.setObjectName("MessageBoxDialog")
        MessageBoxDialog.resize(500, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MessageBoxDialog.sizePolicy().hasHeightForWidth())
        MessageBoxDialog.setSizePolicy(sizePolicy)
        MessageBoxDialog.setMinimumSize(QtCore.QSize(0, 0))
        MessageBoxDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        MessageBoxDialog.setFont(font)
        MessageBoxDialog.setStyleSheet("QDialog {\n"
"    background-color: #FFFFFF;    /* Белый фон окна */\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #0F172A;   /* Акцентный цвет текста */\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #FFFFFF;\n"
"    border: none;\n"
"}")
        MessageBoxDialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(MessageBoxDialog)
        self.verticalLayout.setContentsMargins(16, 24, 16, 16)
        self.verticalLayout.setSpacing(24)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_frame = QtWidgets.QFrame(MessageBoxDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_frame.sizePolicy().hasHeightForWidth())
        self.message_frame.setSizePolicy(sizePolicy)
        self.message_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.message_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.message_frame.setObjectName("message_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.message_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(36)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.message_icon_label = QtWidgets.QLabel(self.message_frame)
        self.message_icon_label.setMinimumSize(QtCore.QSize(64, 64))
        self.message_icon_label.setMaximumSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.message_icon_label.setFont(font)
        self.message_icon_label.setText("")
        self.message_icon_label.setObjectName("message_icon_label")
        self.horizontalLayout.addWidget(self.message_icon_label)
        self.text_frame = QtWidgets.QFrame(self.message_frame)
        self.text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_frame.setObjectName("text_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.text_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.message_text_label = QtWidgets.QLabel(self.text_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_text_label.sizePolicy().hasHeightForWidth())
        self.message_text_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.message_text_label.setFont(font)
        self.message_text_label.setWordWrap(True)
        self.message_text_label.setObjectName("message_text_label")
        self.horizontalLayout_3.addWidget(self.message_text_label)
        self.horizontalLayout.addWidget(self.text_frame)
        self.verticalLayout.addWidget(self.message_frame)
        self.button_frame = QtWidgets.QFrame(MessageBoxDialog)
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.button_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(345, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.action_pushButton = QtWidgets.QPushButton(self.button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.action_pushButton.sizePolicy().hasHeightForWidth())
        self.action_pushButton.setSizePolicy(sizePolicy)
        self.action_pushButton.setMinimumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_pushButton.setFont(font)
        self.action_pushButton.setObjectName("action_pushButton")
        self.horizontalLayout_2.addWidget(self.action_pushButton)
        self.verticalLayout.addWidget(self.button_frame)

        self.retranslateUi(MessageBoxDialog)
        QtCore.QMetaObject.connectSlotsByName(MessageBoxDialog)

    def retranslateUi(self, MessageBoxDialog):
        _translate = QtCore.QCoreApplication.translate
        MessageBoxDialog.setWindowTitle(_translate("MessageBoxDialog", "Dialog"))
        self.message_text_label.setText(_translate("MessageBoxDialog", "TextLabel"))
        self.action_pushButton.setText(_translate("MessageBoxDialog", "Ок"))
