# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/passwordUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasswordDialog(object):
    def setupUi(self, PasswordDialog):
        PasswordDialog.setObjectName("PasswordDialog")
        PasswordDialog.resize(515, 330)
        PasswordDialog.setMinimumSize(QtCore.QSize(515, 330))
        PasswordDialog.setMaximumSize(QtCore.QSize(515, 330))
        PasswordDialog.setStyleSheet("QDialog {\n"
"    background-color: #FFFFFF;    /* Белый фон окна */\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #0F172A;   /* Акцентный цвет текста */\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #FFFFFF;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"\n"
"/* === Акцентная кнопка=== */\n"
"QPushButton {\n"
"    background-color: #2563EB;       /* Основной синий */\n"
"    color: #FFFFFF;                  /* Белый текст */\n"
"    font-weight: bold;               /* Жирный шрифт */\n"
"    border: none;                    /* Без рамки */\n"
"    border-radius: 6px;              /* Скругления */\n"
"    padding: 6px 12px;               /* Отступы для аккуратности */\n"
"}\n"
"\n"
"/* === Наведение (hover) === */\n"
"QPushButton:hover {\n"
"    background-color: #5283EF;       /* Более светлый синий */\n"
"}\n"
"\n"
"/* === Нажатие (pressed / checked) === */\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background-color: #124CC9;       /* Тёмно-синий при клике */\n"
"}\n"
"\n"
"/* === Отключена (disabled) === */\n"
"QPushButton:disabled {\n"
"    background-color: #DEE8FC;       /* Бледно-синий фон */\n"
"    color: #FFFFFF;                  /* Белый текст (можно осветлить при желании) */\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"\n"
"\n"
"/* === Базовый стиль для всех QLineEdit === */\n"
"QLineEdit {\n"
"    background-color: #FFFFFF;       /* Белый фон */\n"
"    border: 1px solid #E2E8F0;       /* Светлая рамка */\n"
"    border-radius: 6px;              /* Скругления */\n"
"    color: #64748B;                  /* Цвет текста */\n"
"    padding: 6px 8px;                /* Внутренние отступы для аккуратности */\n"
"}\n"
"\n"
"/* === При фокусе (активное поле ввода) === */\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;       /* Белый фон */\n"
"    border: 1px solid #2563EB;       /* Синяя рамка */\n"
"    border-radius: 6px;\n"
"    color: #0F172A;                  /* Тёмный текст */\n"
"    outline: none;                   /* Убираем системный контур */\n"
"}\n"
"\n"
"/* === Отключенное состояние === */\n"
"QLineEdit:disabled {\n"
"    background-color: #FFFFFF;       /* Белый фон (не серый) */\n"
"    border: 1px solid #F8FAFC;       /* Очень светлая рамка */\n"
"    border-radius: 6px;\n"
"    color: #E2E8F0;                  /* Бледный текст */\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(PasswordDialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.photo_label = QtWidgets.QLabel(PasswordDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photo_label.sizePolicy().hasHeightForWidth())
        self.photo_label.setSizePolicy(sizePolicy)
        self.photo_label.setMinimumSize(QtCore.QSize(150, 298))
        self.photo_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.photo_label.setText("")
        self.photo_label.setScaledContents(True)
        self.photo_label.setObjectName("photo_label")
        self.horizontalLayout.addWidget(self.photo_label)
        self.actions_frame = QtWidgets.QFrame(PasswordDialog)
        self.actions_frame.setMinimumSize(QtCore.QSize(351, 321))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.actions_frame.setFont(font)
        self.actions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.actions_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.actions_frame.setObjectName("actions_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.actions_frame)
        self.verticalLayout_2.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo_label = QtWidgets.QLabel(self.actions_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label.sizePolicy().hasHeightForWidth())
        self.logo_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.logo_label.setFont(font)
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_2.addWidget(self.logo_label)
        self.password_frame = QtWidgets.QFrame(self.actions_frame)
        self.password_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.password_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.password_frame.setObjectName("password_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.password_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.password_label = QtWidgets.QLabel(self.password_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.verticalLayout.addWidget(self.password_label)
        self.password_lineEdit = QtWidgets.QLineEdit(self.password_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout.addWidget(self.password_lineEdit)
        self.hint_label = QtWidgets.QLabel(self.password_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.hint_label.setFont(font)
        self.hint_label.setStyleSheet("QLabel {\n"
"    color: #64748B;\n"
"}")
        self.hint_label.setObjectName("hint_label")
        self.verticalLayout.addWidget(self.hint_label)
        self.full_mode_pushButton = QtWidgets.QPushButton(self.password_frame)
        self.full_mode_pushButton.setEnabled(False)
        self.full_mode_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.full_mode_pushButton.setFont(font)
        self.full_mode_pushButton.setObjectName("full_mode_pushButton")
        self.verticalLayout.addWidget(self.full_mode_pushButton)
        self.verticalLayout_2.addWidget(self.password_frame)
        self.label = QtWidgets.QLabel(self.actions_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #64748B;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.base_mode_pushButton = QtWidgets.QPushButton(self.actions_frame)
        self.base_mode_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.base_mode_pushButton.setFont(font)
        self.base_mode_pushButton.setObjectName("base_mode_pushButton")
        self.verticalLayout_2.addWidget(self.base_mode_pushButton)
        self.horizontalLayout.addWidget(self.actions_frame)

        self.retranslateUi(PasswordDialog)
        QtCore.QMetaObject.connectSlotsByName(PasswordDialog)

    def retranslateUi(self, PasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        PasswordDialog.setWindowTitle(_translate("PasswordDialog", "Dialog"))
        self.logo_label.setText(_translate("PasswordDialog", "File Archive"))
        self.password_label.setText(_translate("PasswordDialog", "Для входа в полный режим введите пароль:"))
        self.password_lineEdit.setPlaceholderText(_translate("PasswordDialog", "Пароль"))
        self.hint_label.setText(_translate("PasswordDialog", "• Минимум 4 символа"))
        self.full_mode_pushButton.setText(_translate("PasswordDialog", "Войти в полный режим"))
        self.label.setText(_translate("PasswordDialog", "Или"))
        self.base_mode_pushButton.setText(_translate("PasswordDialog", "Обычный режим"))
