# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/passwordUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PasswordDialog(object):
    def setupUi(self, PasswordDialog):
        PasswordDialog.setObjectName("PasswordDialog")
        PasswordDialog.resize(600, 400)
        PasswordDialog.setMinimumSize(QtCore.QSize(600, 400))
        PasswordDialog.setMaximumSize(QtCore.QSize(600, 400))
        PasswordDialog.setStyleSheet("QDialog {\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #0F172A;\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: #FFFFFF;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"\n"
"/* === Secondary buttons === */\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    color: #334155;\n"
"    font-weight: normal;\n"
"    border: 1px solid #64748B;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"/* === Hover === */\n"
"QPushButton:hover {\n"
"    border: 1px solid #8B98AA;\n"
"}\n"
"\n"
"/* === Pressed / Checked === */\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    border: 1px solid #515E71;\n"
"}\n"
"\n"
"/* === Отключена (disabled) === */\n"
"QPushButton:disabled {\n"
"    color: #E2E8F0;\n"
"    border: 1px solid #F8FAFC;\n"
"}\n"
"\n"
"\n"
"\n"
"/* === Base srtyle for all QLineEdit === */\n"
"QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #E2E8F0;\n"
"    border-radius: 6px;\n"
"    color: #64748B;\n"
"    padding: 6px 8px;\n"
"}\n"
"\n"
"/* === Active (Focus) === */\n"
"QLineEdit:focus {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #2563EB;\n"
"    border-radius: 6px;\n"
"    color: #0F172A;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* === Disabled === */\n"
"QLineEdit:disabled {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #F8FAFC;\n"
"    border-radius: 6px;\n"
"    color: #E2E8F0;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(PasswordDialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.photo_label = QtWidgets.QLabel(PasswordDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photo_label.sizePolicy().hasHeightForWidth())
        self.photo_label.setSizePolicy(sizePolicy)
        self.photo_label.setMinimumSize(QtCore.QSize(150, 298))
        self.photo_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.photo_label.setText("")
        self.photo_label.setScaledContents(True)
        self.photo_label.setObjectName("photo_label")
        self.horizontalLayout.addWidget(self.photo_label)
        self.stackedWidget = QtWidgets.QStackedWidget(PasswordDialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.auth_page = QtWidgets.QWidget()
        self.auth_page.setObjectName("auth_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.auth_page)
        self.verticalLayout_2.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo_label = QtWidgets.QLabel(self.auth_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label.sizePolicy().hasHeightForWidth())
        self.logo_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.logo_label.setFont(font)
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_2.addWidget(self.logo_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.password_frame = QtWidgets.QFrame(self.auth_page)
        self.password_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.password_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.password_frame.setObjectName("password_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.password_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.password_label = QtWidgets.QLabel(self.password_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.verticalLayout.addWidget(self.password_label)
        self.password_lineEdit = QtWidgets.QLineEdit(self.password_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout.addWidget(self.password_lineEdit)
        self.hint_label = QtWidgets.QLabel(self.password_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.hint_label.setFont(font)
        self.hint_label.setStyleSheet("QLabel {\n"
"    color: #64748B;\n"
"}")
        self.hint_label.setObjectName("hint_label")
        self.verticalLayout.addWidget(self.hint_label)
        self.full_mode_pushButton = QtWidgets.QPushButton(self.password_frame)
        self.full_mode_pushButton.setEnabled(False)
        self.full_mode_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.full_mode_pushButton.setFont(font)
        self.full_mode_pushButton.setStyleSheet("/* === Accent Button === */\n"
"QPushButton {\n"
"    background-color: #2563EB;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"/* ===Hover === */\n"
"QPushButton:hover {\n"
"    background-color: #5283EF;\n"
"}\n"
"\n"
"/* === Pressed / Checked === */\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background-color: #124CC9;\n"
"}\n"
"\n"
"/* === Disabled === */\n"
"QPushButton:disabled {\n"
"    background-color: #DEE8FC;\n"
"    color: #FFFFFF; \n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}")
        self.full_mode_pushButton.setObjectName("full_mode_pushButton")
        self.verticalLayout.addWidget(self.full_mode_pushButton)
        self.verticalLayout_2.addWidget(self.password_frame)
        self.or_label = QtWidgets.QLabel(self.auth_page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.or_label.setFont(font)
        self.or_label.setStyleSheet("QLabel {\n"
"    color: #64748B;\n"
"}")
        self.or_label.setAlignment(QtCore.Qt.AlignCenter)
        self.or_label.setObjectName("or_label")
        self.verticalLayout_2.addWidget(self.or_label)
        self.base_mode_pushButton = QtWidgets.QPushButton(self.auth_page)
        self.base_mode_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.base_mode_pushButton.setFont(font)
        self.base_mode_pushButton.setObjectName("base_mode_pushButton")
        self.verticalLayout_2.addWidget(self.base_mode_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.change_password_label = QtWidgets.QLabel(self.auth_page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.change_password_label.setFont(font)
        self.change_password_label.setStyleSheet("QLabel {\n"
"    color: #2563EB;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    color: #5283EF;\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    color: #124CC9;\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    color: #DEE8FC;\n"
"}")
        self.change_password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.change_password_label.setObjectName("change_password_label")
        self.verticalLayout_2.addWidget(self.change_password_label)
        self.stackedWidget.addWidget(self.auth_page)
        self.change_password_page = QtWidgets.QWidget()
        self.change_password_page.setObjectName("change_password_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.change_password_page)
        self.verticalLayout_4.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout_4.setSpacing(16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.logo_label_2 = QtWidgets.QLabel(self.change_password_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_label_2.sizePolicy().hasHeightForWidth())
        self.logo_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.logo_label_2.setFont(font)
        self.logo_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label_2.setObjectName("logo_label_2")
        self.verticalLayout_4.addWidget(self.logo_label_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.frame = QtWidgets.QFrame(self.change_password_page)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.old_password_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.old_password_label.setFont(font)
        self.old_password_label.setObjectName("old_password_label")
        self.verticalLayout_3.addWidget(self.old_password_label)
        self.old_password_lineEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.old_password_lineEdit.setFont(font)
        self.old_password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.old_password_lineEdit.setObjectName("old_password_lineEdit")
        self.verticalLayout_3.addWidget(self.old_password_lineEdit)
        self.new_password_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.new_password_label.setFont(font)
        self.new_password_label.setObjectName("new_password_label")
        self.verticalLayout_3.addWidget(self.new_password_label)
        self.new_password_lineEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.new_password_lineEdit.setFont(font)
        self.new_password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new_password_lineEdit.setObjectName("new_password_lineEdit")
        self.verticalLayout_3.addWidget(self.new_password_lineEdit)
        self.hint_label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.hint_label_2.setFont(font)
        self.hint_label_2.setStyleSheet("QLabel {\n"
"    color: #64748B;\n"
"}")
        self.hint_label_2.setObjectName("hint_label_2")
        self.verticalLayout_3.addWidget(self.hint_label_2)
        self.verticalLayout_4.addWidget(self.frame)
        self.change_pushButton = QtWidgets.QPushButton(self.change_password_page)
        self.change_pushButton.setEnabled(False)
        self.change_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.change_pushButton.setFont(font)
        self.change_pushButton.setStyleSheet("/* === Accent Button === */\n"
"QPushButton {\n"
"    background-color: #2563EB;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"/* ===Hover === */\n"
"QPushButton:hover {\n"
"    background-color: #5283EF;\n"
"}\n"
"\n"
"/* === Pressed / Checked === */\n"
"QPushButton:pressed,\n"
"QPushButton:checked {\n"
"    background-color: #124CC9;\n"
"}\n"
"\n"
"/* === Disabled === */\n"
"QPushButton:disabled {\n"
"    background-color: #DEE8FC;\n"
"    color: #FFFFFF; \n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}")
        self.change_pushButton.setObjectName("change_pushButton")
        self.verticalLayout_4.addWidget(self.change_pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.back_auth_label = QtWidgets.QLabel(self.change_password_page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.back_auth_label.setFont(font)
        self.back_auth_label.setStyleSheet("QLabel {\n"
"    color: #2563EB;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    color: #5283EF;\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    color: #124CC9;\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    color: #DEE8FC;\n"
"}")
        self.back_auth_label.setAlignment(QtCore.Qt.AlignCenter)
        self.back_auth_label.setObjectName("back_auth_label")
        self.verticalLayout_4.addWidget(self.back_auth_label)
        self.stackedWidget.addWidget(self.change_password_page)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(PasswordDialog)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(PasswordDialog)

    def retranslateUi(self, PasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        PasswordDialog.setWindowTitle(_translate("PasswordDialog", "Dialog"))
        self.logo_label.setText(_translate("PasswordDialog", "File Archive"))
        self.password_label.setText(_translate("PasswordDialog", "Для входа в полный режим введите пароль:"))
        self.password_lineEdit.setPlaceholderText(_translate("PasswordDialog", "Пароль"))
        self.hint_label.setText(_translate("PasswordDialog", "• Минимум 4 символа"))
        self.full_mode_pushButton.setText(_translate("PasswordDialog", "Полный режим"))
        self.or_label.setText(_translate("PasswordDialog", "Или"))
        self.base_mode_pushButton.setText(_translate("PasswordDialog", "Обычный режим"))
        self.change_password_label.setText(_translate("PasswordDialog", "Изменить пароль"))
        self.logo_label_2.setText(_translate("PasswordDialog", "File Archive"))
        self.old_password_label.setText(_translate("PasswordDialog", "Введите старый пароль:"))
        self.old_password_lineEdit.setPlaceholderText(_translate("PasswordDialog", "Пароль"))
        self.new_password_label.setText(_translate("PasswordDialog", "Введите новый пароль:"))
        self.new_password_lineEdit.setPlaceholderText(_translate("PasswordDialog", "Пароль"))
        self.hint_label_2.setText(_translate("PasswordDialog", "• Минимум 4 символа"))
        self.change_pushButton.setText(_translate("PasswordDialog", "Изменить пароль"))
        self.back_auth_label.setText(_translate("PasswordDialog", "Вернуться на страницу входа"))
